### PR TITLE
Django 2.0 compatibility, and better Python 3 support

### PR DESCRIPTION
**Pull request by jnegro**
I made some changes to support Django 2.0 and added a few things  to improve python 3 support.  Please  test with your test runners to make sure I haven't broken any older functionality, as I tested the best I could.  Thanks!

### CODE REVIEW

**Comment by Brobin** [comment]
@jnegro Thanks! I'm not opposed to just dropping Python 2 support. This is to be used on new projects and Django recommends 2 and is dropping 2 support in a couple years anyway. 

You'll have to remove 2.7 from the build matrix to get the tests to pass

**Comment by jnegro** [comment]
I completely agree.  I made the changes and squashed the commits.  Tests are passing.

**Comment by Brobin** [comment]
Great! Can you remove the future imports now? They're not needed since we're py3 only

**Comment by jnegro** [comment]
Done, and I put in a check in the generate manage file to make sure it's python >=3.4

**Comment by sadaqatullah** [comment]
Does it mean that this library now supports Django 2.0? I am learning Rest and one of the issues in a forked project comes due to this library not supporting 2.0

**Comment by anonyxhappie** [comment]
@Brobin can you review and accept this PR as changes seems correct and all checks pass.
drf-generators doesn't make sense today without django 2 support
thanks

**Comment by Brobin** [comment]
Sorry for the late reply. I'll get this pushed to pypi

**Pull request merged**
